# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.auth.user.email_verification.token.ttl_seconds: 86400 # 24 hours
    app.auth.user.email_verification.token.random_bytes: 32

    app.auth.user.reset_password.token.ttl_seconds: 86400 # 24 hours
    app.auth.user.reset_password.token.random_bytes: 32

    app.auth_log.retention_interval: '12 months'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    App\Service\IpLookup\CompositeIpLookupService: ~
    App\Service\IpLookup\IpWhoisLookupService: ~
    App\Service\IpLookup\RdapLookupService: ~
    App\Service\IpLookup\IpLookupInterface: '@App\Service\IpLookup\CompositeIpLookupService'
